### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by Soro08** [Opeyemi19/Model_Voyage#1]
Explique les modèles

**Comment by Opeyemi19** [comment]
Ok c'est compris Prof

**Comment by Opeyemi19** [comment]
J'ai fais l'explication de mes modèles. Donc vous pouvez vérifier

Le lun. 16 sept. 2019 à 16:50, Sodik Fatayo <sodikfatayo@gmail.com> a
écrit :

> Ok c'est compris Prof
>

**Comment by Soro08** [comment]
Ok
